packages/rrweb/src/record/observer.ts

This seems to just be unavailable sometimes, crashing stuff.
Upstream PR: https://github.com/rrweb-io/rrweb/pull/1088

feat: Guard against missing `window.CSSStyleSheet`

---

LICENSE
README.md

This PR replaces the original rrweb license with our Sentry license. Furthermore, it adjusts the readme to inform about the purpose of this fork and to give attribution to the original authors. 
cc @chadwhitacre
ref #15

chore(repo): Add Sentry license and readme

---

scripts/craft-pre-release.sh

This PR adds a pre-release script that craft executes to set the version of the rrweb packages.
A note on version bumps:
rrweb uses different versions for every package. Since we don't do this in any of our Sentry monorepos, we're going to align the versions of all packages, bumping them to v1.100.0 for the first release. This is the easiest way forward and we're not breaking anything by aligning the versions. 
ref #15

build(repo): Add craft pre-release script

---

.craft.yml

This PR adds the craft config file we need to publish the rrweb packages.

publish(repo): Add Craft config 

---

.craft.yml
package.json
packages/rrdom/LICENSE
packages/rrdom/package.json
packages/rrweb-player/LICENSE
packages/rrweb-player/package.json
packages/rrweb-snapshot/LICENSE
packages/rrweb-snapshot/package.json
packages/rrweb/LICENSE
packages/rrweb/package.json

This PR adds npm scripts to build NPM tarballs. 
Because rrweb uses [release-it](https://github.com/release-it/release-it) for publishing their packages, there was no need to create tarballs before. However, as we're using Craft and we have to put tarballs into the GHA build artifacts for craft to pick them up, we need a script to build them easily. 
Furthermore, release-it seems to have some way of adding the `LICENSE` file to the respective packages. We actually need to copy them into the packages to have them included in the tarballs.
Due to how rrweb set up the `prepack` hook, whenever `yarn build:tarball` is executed, the other build steps (rollup, type checking) are executed automatically beforehand. While this means we're probably gonna execute builds twice in CI, I think this is …

build(repo): Add `build:tarball` scripts

---

.github/workflows/ci-cd.yml
.github/workflows/release.yml

This PR prepares our CI for publishing our packages by 
* adding the "Prepare Release" Github Action (analogously to sentry-javascript or sentry-bundler-plugins)
* uploading build artifacts  to GH which craft pulls when publishing
Draft until #21 and #22 are merged
ref #15

publish(ci): Add "Prepare Release" GHA and Artifacts upload

---

packages/rrdom/package.json
packages/rrweb-player/package.json
packages/rrweb-snapshot/package.json
packages/rrweb/package.json

For the four rrweb packages, the `publishConfig` field in their `package.json`s was missing. This PR adds it with a public config so we can avoid NPM publish throwing an error that these packages are private.

chore(rrweb): Add `publishConfig` field to package.jsons

---

packages/rrweb/src/record/observer.ts

We got one or two bugs that failed due to `event` not being defined.

fix: Handle case where `event` is null/undefined

---

packages/rrweb/src/record/mutation.ts

We got some bugs where `target.style` was undefined, so just try-catching all of this.

fix: Catch style mutation handling

---

packages/rrweb/src/record/observer.ts

Noticed this while debugging tests in sentry-javascript. it seems jsdom has a weird support for `CSSMediaRule`, where it is defined but if you look at `CSSMediaRule.prototype` it is:
```
CSSRule {
parentRule: null,
parentStyleSheet: null,
constructor: [Function: CSSMediaRule],
type: 4
}
```
I guess maybe similar issues have triggered some of the errors we've seen in the past.
Note: We've been handling these errors already, but still good to fix it properly. I'll also PR this upsteam.

fix: Ensure CSS support is checked more robustly

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/html/mask-text.html
packages/rrweb/test/integration.test.ts

If textarea has a child string content, it will get duplicated as a `value` attribute. Masking by text vs input can cause these two values to diverge (i.e. only one is masked). On playback, we remove duplicate textContent for textareas, which means we could show double textarea values: one masked, one unmasked.

fix: masking on textarea 

---

packages/rrweb-snapshot/package.json

`jest-environment-jsdom` should be in `devDependencies`.

fix: Fix accidential `dependencies` of `rrweb-snapshot`

---

packages/rrweb-snapshot/src/rebuild.ts
packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/test/__snapshots__/integration.test.ts.snap
packages/rrweb-snapshot/test/html/preload.html

We were only excluding `<link rel="preload" as="script" />` but we should include `rel="modulepreload"` as well

fix: Exclude `modulepreload` as well

---

packages/rrweb/src/record/mutation.ts

This _may_ be the underlying cause [here](https://sentry.sentry.io/issues/3725692470/?project=11276&referrer=assigned_activity-email), maybe an e.g. `undefined` sneaked in there somehow. IMHO this should also safe some bytes.

fix: more robust `rootShadowHost` check

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/test/html/video.html

These can lead to weird results when replaying this later, so we just want to omit these.
ref: https://github.com/getsentry/sentry-javascript/issues/6602#issuecomment-1438801706

feat: Remove `autoplay` attribute from audio/video tags

---

packages/rrweb/src/index.ts

Let's export all of these types so we can use them.

feat(types): Export `typings/types`

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb-snapshot/test/__snapshots__/integration.test.ts.snap
packages/rrweb-snapshot/test/html/form-fields.html
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/html/empty.html
packages/rrweb/test/integration.test.ts

Fix bug introduced in https://github.com/getsentry/rrweb/pull/43 where we masked both textarea's `value` and `textContent`, which meant the text inside of the textarea would get duplicated. We can ignore `textContent` in this case and set it to an empty string.

fix: textarea value is being duplicated

---

.github/workflows/ci-cd.yml
packages/rrweb/typings/index.d.ts

Previously, in the "Upload Artifacts" job, we didn't explicitly run a build command but instead relied on the package-specific `prepack` yarn scripts. This caused an incomplete `@sentry-internal/rrweb-player` package, as this package didn't have a `prepack` script. This PR now adds a step to the CI job to actually run the `prepublish` build command before packing the tarballs. 
I checked the resulting tarball against the actual rrweb player and it seems all files are present now. Uploaded artifacts of a test branch: https://github.com/getsentry/rrweb/actions/runs/4263220937
Misc: This PR also updates a type declaration file that was stale beforehand. 
closes #63

fix(build/CI): Run prepublish scripts before building tarballs

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb-snapshot/typings/utils.d.ts
packages/rrweb/src/record/observer.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/html/form-masked.html
packages/rrweb/test/html/form.html
packages/rrweb/test/integration.test.ts

Since `maskInputSelector` is a new configuration item, we were not handling the case for input change when `maskAllInputs:false`. Before, input masking was only done via `maskInputOptions` and `maskAllInputs`.

fix: masking inputs on change when `maskAllInputs:false`

---

packages/rrweb-snapshot/src/rebuild.ts
packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/types.ts
packages/rrweb-snapshot/typings/snapshot.d.ts
packages/rrweb-snapshot/typings/types.d.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/integration.test.ts

This adds on top of https://github.com/getsentry/rrweb/pull/65 and adds a test for this, as well as streamlining this check in the `transformAttribute` method.

PR fix: Add test for null attribute

---

packages/rrweb-snapshot/src/rebuild.ts
packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/types.ts
packages/rrweb-snapshot/typings/snapshot.d.ts
packages/rrweb-snapshot/typings/types.d.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/integration.test.ts

Fixes https://github.com/getsentry/sentry-javascript/issues/7278

fix(snapshot): Handle removed attributes

---

packages/rrweb/src/record/index.ts
packages/rrweb/src/record/observer.ts
packages/rrweb/src/types.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/integration.test.ts
packages/rrweb/typings/types.d.ts

When this callback returns `false`, we skip handling the mutations normally. It's up to the host app to do something with this then.
Replaces https://github.com/getsentry/rrweb/pull/58

feat: Add `onMutation` option to `record`

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/typings/snapshot.d.ts
packages/rrweb/src/record/mutation.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/html/form.html
packages/rrweb/test/integration.test.ts

This should be considered "Text", and should thus be masked by `maskAllText`.
This is both for `<input type='button'>` as well as `<input type='submit'>`.
Closes https://github.com/getsentry/rrweb/issues/68

fix: Ensure `<input type='submit' value='Btn text'>` is masked

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/types.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb-snapshot/typings/types.d.ts
packages/rrweb/src/record/index.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/html/form.html

This ensures we mask `<option>` when selects should be masked.
We mask both the `value` attribute as well as the text content of the `<option>`.
note that due to how masking work, the replay _may_ not look completely correct. E.g. if you have the following:
```html
<select name="" id="" value="BB">
<option value="AA">A</option>
<option value="BB">My B</option>
</select>
```
it is masked to:
```html
<select name="" id="" value="**">
<option value="**">*</option>
<option value="**">****</option>
</select>
```
since technically both options have the same "value" now, when a user selects an option it may not reflect the longer text in the select box. However, I'd say that is OK, and better than to leak the values. 
In addition, this also makes sure to mask `value` of radio/checkbox inputs. …

fix: Mask `<option>` values for selects & radio/checkbox `value`

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/types.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb-snapshot/typings/types.d.ts
packages/rrweb/src/record/index.ts
packages/rrweb/src/record/mutation.ts
packages/rrweb/src/record/observer.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/html/form.html
packages/rrweb/test/html/password.html
packages/rrweb/test/integration.test.ts

This PR does two things:
1. Ensure you cannot opt-out of masking `type="password"` inputs
2. Ensure inputs that used to have `type=password` and have this type changed (so e.g. through a "show password" toggle) always keep the password masked, even afterwards.
We should never record passwords, and e.g. `toggle password` type buttons are quite common and would easily leak the password into the replay as of now.
We do this by adding a `rr_is_password` attribute to the HTML input when the type is changed from `password` to something else. This is IMHO the easiest solution for this, and since we only add this when the type is really changed (so not eagerly for all inputs) IMHO it's an acceptable tradeoff to have this in the DOM.
Closes https://github.com/getsentry/rrweb/issues/34

feat: Ensure password inputs are always masked

---

packages/rrweb/src/replay/index.ts

For some reason we have some recordings that have duplicated node ids. Not sure how widespread this is, but lets check for dupes before appending a mutation.

feat(replay): Check for node existance in mirror before appending

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/typings/snapshot.d.ts
packages/rrweb/src/record/mutation.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/html/attributes-mask.html
packages/rrweb/test/integration.test.ts

Closes https://github.com/getsentry/rrweb/issues/79

fix: Ensure unmaskTextSelector is used for masked attributes

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/typings/snapshot.d.ts
packages/rrweb/src/record/observer.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/integration.test.ts

We had inconsistent casing for the tagName, leading to some masking slipping through.

fix: Ensure text masking for updated attributes works

---

packages/rrweb/src/replay/index.ts
packages/rrweb/test/__snapshots__/replayer.test.ts.snap
packages/rrweb/typings/replay/index.d.ts

We turned `pointer-events` on in our client so that our users can use browser tools to "inspect" the dom. Without `pointer-events`, users hovering over elements in the replay would not reflect in the dev tools.
A side-effect of enabling `pointer-events` was that users would be able to click links in the Replay and end up breaking everything. e.g. "Looks like your Replayer was destroyed"

feat: Use JS to disable clicks in Replayer

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb-snapshot/typings/utils.d.ts
packages/rrweb/src/record/mutation.ts
packages/rrweb/src/record/observer.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap

This brings a few further fixes to input masking (esp. for radio buttons), which we also fixed/are in the process of fixing upstream.
Also this aligns some things with how they have been fixed upstream, to make a future merging easier.

fix: Fix some input masking & align with upstream

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/test/css.test.ts
packages/rrweb-snapshot/typings/snapshot.d.ts

Safari does not escape `:` in attribute selectors correctly, so we need to do that instead.
See https://github.com/rrweb-io/rrweb/issues/1208
ref https://github.com/getsentry/sentry-javascript/issues/7703

fix: Fix CSS rules captured in Safari

---

packages/rrweb-snapshot/src/rebuild.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb-snapshot/typings/utils.d.ts
packages/rrweb/src/replay/index.ts
packages/rrweb/test/events/shadowDom.ts
packages/rrweb/test/replayer.test.ts

Define custom elements so that we the `:defined` pseudo-class works as it can be used as a "loading" indicator while the web component is being loaded.
Fixes https://github.com/getsentry/sentry-javascript/issues/7988

feat(replay): Define custom elements (web components)

---

LICENSE

While setting up the publishing process for our `rrweb` fork, we changed the `LICENSE` text (#18) to our standard MIT license. This was recently pointed out in https://github.com/rrweb-io/rrweb/issues/1248. While It's worth noting that our fork was also always MIT-licensed, we did changed the copyright, which incorrectly suggested that the repo's code was ours. While I'm not entirely sure what the reason for the change was back then, in hindsight this shouldn't have happened and I'm sorry for causing any confusion associated with this change. 
This PR adjusts the `LICENSE` file to include both, rrweb's original license as well as our license text, which is what we settled on after internal conversations (see https://github.com/getsentry/rrweb/pull/91#issuecomment-1623839222).
rendered …

chore: Include original rrweb and Sentry licenses

---

packages/rrweb/src/record/observer.ts

Calling `Object.getOwnPropertyDescriptor(undefined, 'xx')` actually errors out, so let's probably guard there.

fix: Fix checking for `patchTarget` in `initAdoptedStyleSheetObserver`

---

packages/rrweb/src/record/iframe-manager.ts
packages/rrweb/src/record/index.ts
packages/rrweb/src/record/observers/canvas/canvas-manager.ts
packages/rrweb/src/record/shadow-dom-manager.ts
packages/rrweb/src/types.ts

This PR adds 3 new build flags to rrweb:
* `__RRWEB_EXCLUDE_CANVAS__`
* `__RRWEB_EXCLUDE_SHADOW_DOM__`
* `__RRWEB_EXCLUDE_IFRAME__`
If you set these to `true` at build time, it will replace the regular `ShadowDomManager` / `CanvasManager` / `IframeManager` with a noop variant of these managers.
All of these together shave off about 8 KB gzipped from our replay bundles, if set to `true`.
For now, we'll probably keep this enabled by default, but at least we have a path for users to shake this out if they don't need these features.
Note: I played with some other approaches, e.g. instead of having the noop class make these e.g. `iframeManager: IframeManager | undefined`, but I think overall the code to guard against using this everywhere ends up being a similar amount of bytes, plus we need …

feat: Add build flags to allow noop iframe/canvas/shadow dom managers

---

packages/rrweb-snapshot/src/rebuild.ts

Dimensions are not being properly applied when you seek to a position in the replay. Need to use `setProperty`, otherwise the style attributes get lost.

fix: dimensions not being applied

---

.github/workflows/size-check.yml
.size-limit.js
package.json
packages/rrweb/src/record/observers/canvas/2d.ts
packages/rrweb/src/types.ts
packages/web-extension/vite.config.ts
yarn.lock

Add action for size limit info, similar to the sentry-javascript repo.
This should make it much easier to check the impact of changes.

build: Add size limit action

---

packages/rrweb/src/replay/index.ts

Fixes JAVASCRIPT-2MPK
Closes https://github.com/getsentry/team-replay/issues/216

fix(rrweb): Fix `rule.style` being undefined

---

packages/rrweb/src/index.ts
packages/rrweb/src/record/index.ts
packages/rrweb/test/record.test.ts

Currently, we use these from `record.xx`, which is not ideal thinking about treeshaking and lazy loading.
This moves these to be proper exports so we can use the in Replay without having to import `record` and everything that comes with it (=everything).

feat: Refactor module scope vars & export `mirror` & `takeFullSnapshot` directly

---

packages/rrweb/src/record/index.ts

We are always passing in fresh objects to this method, so instead of cloning this into a new object, we can just put the `timestamp` on the given object directly and return it, saving a bit of processing cost.

ref: Avoid cloning events to add `timestamp`

---

packages/rrweb/src/record/observer.ts
packages/rrweb/src/record/observers/canvas/2d.ts
packages/rrweb/src/record/observers/canvas/serialize-args.ts
packages/rrweb/src/record/observers/canvas/webgl.ts

Small refactors to avoid unnecessary work being done.

ref: Avoid unnecessary cloning of objects or arrays

---

packages/rrweb/src/record/index.ts
packages/rrweb/src/record/observer.ts

We do not use this, so removing this reduces some overhead & bundle size.

feat: Remove `hooks` related code, which is not used

---

README.md
packages/rrweb/src/record/index.ts
packages/rrweb/src/record/observer.ts

1. Add notes on major changes in this fork
2. Refactor a previous change a bit in order to keep line breaks etc. better aligned with upstream, in order to prevent future merge conflicts

ref: Docs & mergability improvements

---

.size-limit.js
packages/rrweb/src/index.ts
packages/rrweb/src/record/index.ts
packages/rrweb/src/record/observers/canvas/canvas-manager.ts
packages/rrweb/src/types.ts
packages/rrweb/test/record/cross-origin-iframes.test.ts
packages/rrweb/test/record/webgl.test.ts
packages/rrweb/test/utils.ts

This PR exports a new `getCanvasManager()` method which can be used to dynamically pass a canvas manager, allowing tree shaking.
This also removes the `__RRWEB_EXCLUDE_CANVAS__` build flag - canvas will _always_ be excluded now by default.
Expected usage:
```js
import { record, getCanvasManager } from '@sentry-internal/canvas';
record({
// other config...
getCanvasManager,
});
```
The idea is that we can expose this somehow (?) from replay, so users can do e.g.:
```js
import { Replay, getReplayCanvasManager } from '@sentry/browser';
Sentry.init({
integrations: [
new Replay({ canvasManager: getReplayCanvasManager() })
]
});
```
Or something like this, allowing people to opt-in to canvas recording at runtime, vs requiring a specific build step for it.

feat: Export `getCanvasManager` & allow passing it to `record()`

---

packages/rrweb-snapshot/src/rebuild.ts

Large stylesheets will cause `addHoverClass` to block the main UI thread when viewing a replay. Turn this off when stylesheet is >= 1MB.

feat(replay): Skip `addHoverClass` when stylesheet is >= 1MB

---

packages/rrweb/src/index.ts

We need these types/functions to replay canvas.

feat: Export additional canvas-related types and functions

---

.changeset/stupid-ghosts-help.md
packages/rrweb/src/record/index.ts

This reverts commit 3416c3a769e2bd2ddfbb88f5c4ff139871c567be.
From [my comment here](https://github.com/rrweb-io/rrweb/issues/1242#issuecomment-1847812047)
> I only used translate on the OP but if I understand correctly, when we call `takeFullSnapshot(true)`, we will receive two distinct events with the `isCheckout` arg as `true`. Looking at the blame this is due to #1141.
> If you use `checkoutEvery...` and rely on `isCheckout` to reset existing events, this means that the [`Meta` event](https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/index.ts#L352-L362) will be lost because [the `FullSnapshot`](https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/index.ts#L408-L417) occurs afterwards, and `isCheckout` is true for both events. Losing the `Meta` …

Revert "fix: isCheckout is not included in fullsnapshot event (#1141)"

---

packages/rrweb/src/record/index.ts

From what I can tell, `record` ends up getting bundled separate from `getCanvasManager` in user-land code and canvas mutation events end up not being transmitted because `_wrappedEmit` does not get set and it will hold the wrong `mirror` reference.

feat(canvas): Bind `mutationCb` outside of `getCanvasManager`

---

packages/rrdom-nodejs/tsconfig.json
packages/rrdom/tsconfig.json
packages/rrvideo/tsconfig.json
packages/rrweb-snapshot/tsconfig.json
packages/rrweb/tsconfig.json
packages/types/tsconfig.json
packages/web-extension/tsconfig.json

Avoid already polyfilling stuff in here - we rather do this in the Sentry SDK directly.
Currently, we are polyfilling things separately here (e.g. rest parameters, async/await), but we would polyfill stuff we need more efficiently in the Sentry SDK anyhow. So this should reduce bundle size a bit.

build: Build for ES2020

---

packages/rrdom-nodejs/package.json
packages/rrdom-nodejs/rollup.config.js
packages/rrdom-nodejs/tsconfig.json
packages/rrdom/package.json
packages/rrdom/rollup.config.js
packages/rrdom/tsconfig.json
packages/rrweb-player/package.json
packages/rrweb-player/rollup.config.js
packages/rrweb-player/tsconfig.json
packages/rrweb-worker/.eslintrc.json
packages/rrweb-worker/.gitignore
packages/rrweb-worker/package.json
packages/rrweb-worker/rollup.config.js
packages/rrweb-worker/src/_image-bitmap-data-url-worker.ts
packages/rrweb-worker/src/image-bitmap-data-url-worker.ts
packages/rrweb-worker/src/index.ts
packages/rrweb-worker/tsconfig.json
packages/rrweb-worker/tsconfig.types.json
packages/rrweb/package.json
packages/rrweb/rollup.config.js
packages/rrweb/src/record/observers/canvas/canvas-manager.ts
packages/rrweb/src/record/workers/tsconfig.json
packages/rrweb/src/record/workers/workers.d.ts
packages/rrweb/tsconfig.json
tsconfig.json
yarn.lock

While trying to get the ReplayCanvas integration to properly tree shake, I noticed that the current way this worker is built is not ideal, and maybe is not treeshakeable properly. We use a rollup plugin to convert the worker to a base64 string, which a) is more verbose than just having the worker be a plain string, and b) possibly is not tree shakeable.
This refactors the worker to work the same way as the compression worker in Sentry - we build it to a string and use that in rrweb. This is a bit more complicated, from a setup perspective, but gives us full control over the worker build.

feat: Bundle canvas worker manually

---

packages/rrweb/src/record/observers/canvas/canvas-manager.ts

Related to https://github.com/getsentry/rrweb/pull/142, noticed that this is kind of unnecessary (and is transpiled in pre-ES2017 envs). Passing an async function to forEach is anyhow a bit weird I'd say.

ref: Avoid async in canvas

---

CHANGELOG.md

Some build improvements, let's see if they help with the canvas manager tree shaking...

meta(changelog): Update changelog for 2.7.0

---

packages/rrweb-worker/package.json

I think this is what blew up the build (https://github.com/getsentry/publish/actions/runs/7277054052/job/19828232668), seems that craft tried to publish this incorrectly to NPM 😬

build: Do not build rrweb-worker package

---

packages/rrweb/src/record/observers/canvas/canvas-manager.ts
packages/rrweb/src/record/processed-node-manager.ts
packages/rrweb/src/replay/timer.ts
packages/rrweb/src/utils.ts

As explained here: https://github.com/getsentry/sentry-javascript/issues/6946#issuecomment-1875842171 the usage of `requestAnimationFrame` can lead to issues when working with Zone.js.
With this fix, where possible we should now use the `requestAnimationFrame` implementation from an iframe, if possible, and else fall back on just using `window.requestAnimationFrame` as before.
We already do something similar in sentry-javascript to get an unpatched `fetch`: https://github.com/getsentry/sentry-javascript/blob/23ef22b115c8868861896cc9003bd4bb6afb0690/packages/browser/src/transports/utils.ts#L65-L71 so this should hopefully work fine!

fix(rrweb): Use unpatched `requestAnimationFrame` when possible

---

.github/workflows/ci-cd.yml

Not 100% sure, but I _think_ this is the cause of publish failing here: https://github.com/getsentry/rrweb/actions/runs/7277648321/job/19830279475

build(ci): Ensure we build properly before building tarballs

---

CHANGELOG.md
packages/rrweb-worker/tsconfig.json
packages/rrweb/package.json
packages/rrweb/tsconfig.json

It is now complaining:
```
error Couldn't find package "@sentry-internal/rrweb-worker@2.7.2" required by "@sentry-internal/rrweb@2.7.2" on the "npm" registry.
```
hopefully this is fixed by making this a devDependency.

build: Fix build issue with rrweb & rrweb-worker

---

packages/rrweb/src/record/index.ts

Catches exceptions thrown from `getCanvasManager` and returns the Noop version so that replay recording can continue.
Fixes https://sentry.sentry.io/issues/4745239659/?project=11276

feat(replay): Catch exceptions from `getCanvasManager`

---

.size-limit.js
packages/rrweb/src/index.ts
packages/rrweb/src/record/index.ts
packages/rrweb/src/types.ts
packages/rrweb/test/record/cross-origin-iframes.test.ts
packages/rrweb/test/record/webgl.test.ts
packages/rrweb/test/utils.ts

This simplifies the code a bit by exporting the CanvasManager directly. With [ReplayCanvas](https://github.com/getsentry/sentry-javascript/pull/10112), we can rely on it for complex setup, but keeps it simple for our users.

feat: Remove `getCanvasManager`, export `CanvasManager` class directly

---

packages/rrweb-snapshot/src/snapshot.ts

try/catch to protect against cases where `el.matches` is not a function (not sure exact cause, but possibly `el` is undefined, or not an Element type)

fix: Protect against `matches()` being undefined

---

packages/rrweb-snapshot/src/snapshot.ts

Probably fixes https://github.com/getsentry/sentry-javascript/issues/10292
Not sure how `attr.name` could be undefined here but according to the issue, it happens and we should probably guard adding the attribute.
Open question (see my comment)

fix(snaptshot): Ensure `attr.name` is defined when collecting element attributes

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb/src/record/index.ts
packages/rrweb/src/record/observers/canvas/canvas-manager.ts

Needed as we (Sentry), codesplit CanvasManager. Also fixes uncaught exceptions from `createImageBitmap`

feat: Register `errorHandler` inside of CanvasManager

---

packages/rrweb/src/replay/index.ts

Not sure why this happens.
Fixes JAVASCRIPT-2P6F

fix(replayer): `<style>` node `rules` attr can be undefined

---

packages/rrweb/src/record/iframe-manager.ts
packages/rrweb/src/record/observer.ts

cherry-picks https://github.com/rrweb-io/rrweb/pull/1155 which was merged in our fork in https://github.com/getsentry/rrweb/pull/107 (prior to #1155 being merged). This results in only 2 small stylistic changes.
Feat: Add support for replaying :defined pseudo-class of custom elements #1155

upstream: Feat: Add support for replaying :defined pseudo-class of custom elements (#1155)

---

packages/rrweb-snapshot/test/__snapshots__/integration.test.ts.snap
packages/rrweb-snapshot/test/html/form-fields-sensitive-update.html
packages/rrweb-snapshot/test/html/form-fields-sensitive.html
packages/rrweb/test/__snapshots__/integration.test.ts.snap

This tests masking of initial & updated values for password & credit card fields.
You can see that for now credit card data is not masked, which demonstrates the current behavior. 
In a future PR we can then verify that our fixed masking is working.
ref https://github.com/getsentry/sentry-javascript/issues/10258

test: Add tests for masking of sensitive data

---

packages/rrweb-snapshot/src/css.ts
packages/rrweb-snapshot/test/css.test.ts

This fixes a parsing issue of CSS selectors that use a functional pseudo class with multiple arguments.
For example,
```
.foo:has(button,div) {}
```
Would get parsed as 2 selectors: `.foo:has(button` and `div)` - this results in an invalid stylesheet and looks like the replay is broken.

fix: Incorrect parsing of functional pseudo class css selector

---

packages/rrweb/src/record/index.ts
packages/rrweb/src/replay/index.ts

Fixes several cases where we access an undefined value.
In the case of `lastFullSnapshotEvent`, it can be undefined if we receive an incremental event before a full snapshot. This can happen, for example, if a user refreshes while canvas worker is working and on reload it finishes to call the mutation callback and before fullsnapshot occurs.
Fixes JAVASCRIPT-2S3R
Fixes JAVASCRIPT-2QS1
Fixes JAVASCRIPT-2FQ5
Fixes JAVASCRIPT-2H2H

fix: fixes several cases where we access an undefined value

---

packages/rrweb/src/record/observer.ts
packages/rrweb/src/record/observers/canvas/2d.ts
packages/rrweb/src/record/shadow-dom-manager.ts
packages/rrweb/src/replay/index.ts
packages/rrweb/src/utils.ts

Let's see if that helps with Angular performance some more...!
Closes https://github.com/getsentry/sentry-javascript/issues/11661 (hopefully...)

feat: Ensure to use unwrapped versions of `setTimeout` / `clearTimeout`

---

packages/rrweb/src/record/mutation.ts

* only call createHTMLDocument where it is needed
* Perf: create the mutation document once as a 'singleton' as it can be reused
---------
Co-authored-by: Michael Dellanoce <mdellanoce@pendo.io>

upstream: perf: only call `createHTMLDocument` where it is needed 

---

.changeset/event-single-wrap.md
packages/rrweb/src/record/iframe-manager.ts
packages/rrweb/src/record/index.ts
packages/rrweb/test/utils.ts
packages/types/src/index.ts

performance: remove a nested function call and an object clone during event emission
- rename `event` to `eventWithoutTime`, but maintain backwards compatibility
- `eventWithTime` (with time) could be renamed to `event` in a future version
This is an extension of PR #1339 authored by: mydea <mydea@users.noreply.github.com>

upstream: perf: Avoid an extra function call and object clone during event emission

---

packages/rrweb/src/record/observers/canvas/canvas-manager.ts

To keep this compatible with prior versions, this option should be optional. This won't affect sentry SDK, but if we want to submit this upstream, it needs to be optional.

fix: Change `maxCanvasSize` to be optional

---

.changeset/rotten-spies-enjoy.md
packages/rrweb-snapshot/src/css.ts
packages/rrweb-snapshot/src/index.ts
packages/rrweb-snapshot/src/rebuild.ts
packages/rrweb-snapshot/test/css.test.ts
packages/rrweb-snapshot/test/rebuild.test.ts

This reverts https://github.com/getsentry/rrweb/pull/182 (i.e. we are going back to https://github.com/getsentry/rrweb/pull/169) as we had some performance regressions with the CSS changes.
I tested these against the replays that had crashed with the upstream changes and they seem to work ok.

fix: fix css parsing in replayer

---

.changeset/eleven-bobcats-peel.md
packages/rrweb/src/record/index.ts
packages/rrweb/src/types.ts

This work is to try to provide support where rrweb might be included
in applications with various tools that might override Array.from
so that the 2nd parameter (the map function) will always work for
rrweb.
Authored-by: Michael Dellanoce <mdellanoce@pendo.io>

upstream: Replace Array.from with clean implementation

---

packages/rrweb/src/replay/index.ts
packages/rrweb/test/__snapshots__/replayer.test.ts.snap
packages/rrweb/test/replayer.test.ts

this change allows us to draw multiple "mousetails" at once.
ios replay BEFORE: only one tail showing up
https://github.com/getsentry/rrweb/assets/56095982/05b5bc8a-b600-4a34-929f-fb9fcc4acd5f
ios replay AFTER: both tails showing up & clearing properly:
https://github.com/getsentry/rrweb/assets/56095982/99f74e19-b1e6-402e-a766-ce0d22a0851b

fix(rrweb): allow for drawing multiple mousetails

---

.gitignore
packages/rrweb-snapshot/package.json
packages/types/package.json

This is needed to include the downleveled typings in our dist package.

fix(ts): Forgot to include 3.8 typings dirs in `files`

---

packages/rrweb/src/replay/index.ts

fixes [JAVASCRIPT-2THH](https://sentry.sentry.io/issues/5473658404/)
we remove the `pointerEl` when a `TouchEnd` event occurs, so we need to do a null check to make sure it exists before trying to access its properties.

fix(rrweb): null check for pointerEl

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/utils.ts

Use unpatched `setTimeout` and `clearTimeout` to ensure that we are not triggering Angular change detection when snapshotting.

feat(snapshot): Use unpatched `setTimeout` and `clearTimeout`

---

packages/rrweb/src/record/observers/canvas/canvas-manager.ts

Need to move this up so window is added in the case where we have manual snapshots.

fix(canvas): Fix missing `addWindow` call when `enableManualSnapshot==true`

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/test/snapshot.test.ts

Do not attempt to access `contentDocument` of iframe if element is blocked, otherwise it will trigger a browser warning. e.g.
`Blocked a frame with origin "<foo>" from accessing a frame with origin "<bar>". Protocols, domains, and ports must match.`
Fixes https://github.com/getsentry/sentry-javascript/issues/6560

feat(snapshot): Check "blocked" status of iframes before accessing `contentDocument`

---

packages/types/package.json
yarn.lock

Use latest git sha of downlevel-dts

fix: Missed downlevel-dts dep in types, update git sha

---

packages/rrweb/src/replay/index.ts
packages/rrweb/test/events/is-sync-tap.ts
packages/rrweb/test/replayer.test.ts

- fixes https://github.com/getsentry/sentry/issues/72959
- cleans up the tap circles when the user seeks by breadcrumb (aka when `isSync` is true) so that there aren't a bunch left on the screen at once
- verified that with this change, multitouch still works correctly
before:
https://github.com/getsentry/rrweb/assets/56095982/6ab6b903-1bb3-494d-8f6e-9e27cf97f199
after (video also shows playback working normally):
https://github.com/getsentry/rrweb/assets/56095982/610fe5e5-1615-4eb5-8837-4ac5e4df1a05

fix(rrweb): clean up pointer tap circles when seeking by breadcrumb

---

packages/rrweb/src/record/mutation.ts
packages/rrweb/test/__snapshots__/integration.test.ts.snap
packages/rrweb/test/integration.test.ts

This fixes a bug with blocking iframes that are dynamically added to the DOM after the snapshot is taken. This ensures we check if iframe is considered blocked before adding to iframe manager.
Closes https://github.com/getsentry/sentry-javascript/issues/13173

feat: Fix blocking dynamically added iframes

---

packages/rrweb/src/record/observers/canvas/canvas-manager.ts

I followed [Set Up Session Replay | Sentry for Javascript](https://docs.sentry.io/platforms/javascript/session-replay/#3d-and-webgl-canvases) and got CPU high usage. 
The takeCanvasSnapshots should not be in rAF loop when the `isManualSnapshot` is true. I also checked the [rrweb/packages/rrweb/src/record/observers/canvas/canvas-manager.ts at master · rrweb-io/rrweb](https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/observers/canvas/canvas-manager.ts#L172) and confirmed it's Sentry customized logic.

fix: manual snapshot in rAF loop

---

packages/rrdom/src/diff.ts
packages/rrdom/test/diff.test.ts

We encountered an issue where replays with invalid attributes (e.g. `@click`) would break rendering the replay after seeking. The exception bubbles up to [here](https://github.com/rrweb-io/rrweb/blob/62093d4385a09eb0980c2ac02d97eea5ce2882be/packages/rrweb/src/replay/index.ts#L270-L279), which means the replay will continue to play, but the replay mirror will be incomplete.
Closes https://github.com/getsentry/team-replay/issues/458

fix(rrdom): Ignore invalid DOM attributes when diffing

---

packages/rrweb/src/record/observers/canvas/canvas-manager.ts

`reset()` gets called when we stop a recording in progress. There is no reason to re-initialize the worker in `reset()` as you would need to call `record()` to start recording again, which would start a new worker. This was introduced in https://github.com/getsentry/rrweb/pull/168.

fix(rrweb): Do not re-initialize worker in CanvasManager.reset

---

packages/rrdom/src/diff.ts
packages/rrdom/src/index.ts
packages/rrdom/src/util.ts
packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb-snapshot/src/utils.ts
packages/rrweb/src/record/iframe-manager.ts
packages/rrweb/src/record/mutation.ts
packages/rrweb/src/record/shadow-dom-manager.ts
packages/rrweb/src/replay/index.ts

closes https://github.com/getsentry/sentry-javascript/issues/14313

fix: Catch calls to iframe content document

---

packages/rrweb-snapshot/src/utils.ts
packages/rrweb/test/__snapshots__/record.test.ts.snap
packages/rrweb/test/record.test.ts

Adds a workaround for [this Chrome bug](https://issues.chromium.org/issues/41416124) where the CSS property `all` gets expanded by Chrome and can potentially override user defined CSS.
Ref https://github.com/getsentry/team-replay/issues/504
```
.btn {
all: unset;
padding: 10px 15px;
}
```
```css
.btn {
color: unset;
font: unset;
font-palette: unset;
font-synthesis: unset;
forced-color-adjust: unset;
text-orientation: unset;
text-rendering: unset;
-webkit-font-smoothing: unset;
-webkit-locale: unset;
-webkit-text-orientation: unset;
-webkit-writing-mode: unset;
writing-mode: unset;
zoom: unset;
accent-color: unset;
place-content: unset;
place-items: unset;
place-self: unset;
alignment-baseline: unset;
animation-composition: unset;
animation: unset;
app-region: unset;
appearance: unset; …
```

fix(snapshot): Fix CSS expansion of `add` CSS property

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb/test/__snapshots__/record.test.ts.snap
packages/rrweb/test/record.test.ts

When in-lining CSS for remote CSS, set attributes to `null` instead of deleting the attributes. The former does not generate a mutation for the attributes. Also include `crossorigin` as an attribute to be removed.

fix(snapshot): Set `<link>` attributes to null for remote CSS

---

packages/rrweb/src/replay/index.ts
packages/rrweb/test/__snapshots__/replayer.test.ts.snap
packages/rrweb/test/replayer.test.ts
packages/rrweb/test/utils.ts

This fixes an issue where inlined CSS from a remotely loaded `<link>` does not get applied properly due to object reference mutation.

fix: remote CSS does not get rebuilt properly

---

packages/rrweb-snapshot/src/rebuild.ts
packages/rrweb-snapshot/src/snapshot.ts

... removes requirement to have `as="script"` attribute. Also fixes prefetch to extract file extension instead of checking end of string since there can be URL parameters.

fix(snapshot): Change to ignore all `link[rel="modulepreload"]`

---

packages/rrweb/test/record/cross-origin-iframes.test.ts

Re-enables test that was skipped in https://github.com/getsentry/rrweb/pull/172;

test(rrweb): Re-enable skipped test

---

packages/rrdom/src/diff.ts
packages/rrdom/test/diff.test.ts
packages/rrweb/test/events/moving-style-sheet-on-diff.ts
packages/rrweb/test/replayer.test.ts

fix code for nodejs tests
change fix direction to avoid issues with duplicate styles
format issues
swap waitForTimeout for waitForRAF in test that flaked
Add unit tests for new functions
Fix broken test causes by file formatting removing spaced
---------
Co-authored-by: jaj1014 <ajax@pendo.io>
Co-authored-by: jaj1014 <jaj1014@users.noreply.github.com>

fix: inserted styles lost when moving elements

---

.github/workflows/style-check.yml

I think this needs to be in main branch for it to work

ci: fix `download-artifact` deprecation, upgrade eslint-annotate-action

---

packages/rrweb-snapshot/src/snapshot.ts

Do not attach a `load` event listener to an iframe that is blocked. This should solve the problem where Safari will complain about accessing a frame from a different origin.
Closes https://github.com/getsentry/sentry-javascript/issues/13173

fix(snapshot): Do not attempt to load iframe at all if it is blocked

---

packages/rrweb-snapshot/src/rebuild.ts

`createCDATASection` is [only supported on XMLDocument](https://developer.mozilla.org/en-US/docs/Web/API/Document/createCDATASection#notes), not HTMLDocument. Doing so on HTMLDocument will throw an exception and break playback on the player.
This change will log a "Failed to rebuild" warning to the console instead of throwing.
Fixes https://sentry.sentry.io/issues/5222059335/?project=11276&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=90d&stream_index=11

fix(snapshot): Do not create CDATA node on HTMLDocument

---

packages/rrweb/src/record/observers/canvas/canvas-manager.ts

In CanvasManager, catch exceptions when accessing `window.document` as it can throw a `SecurityError`:
"SecurityError: Failed to read a named property 'document' from 'Window': An attempt was made to break through the security policy of the user agent."
Fixes [JAVASCRIPT-2X1A](https://sentry.sentry.io/issues/6124877975/events/dcd238939c8147e2b97bb7fc510f1b5a/)

fix(record): Catch exceptions when accessing `window.document`

---

packages/rrweb/src/utils.ts

Access to `node.nodeType` can throw on FF when using the internal screenshot tool.
closes https://github.com/getsentry/sentry-javascript/issues/15559

fix(utils): Safely access `node.nodeType`

---

packages/rrweb-snapshot/src/snapshot.ts
packages/rrweb/src/record/mutation.ts

See https://developer.mozilla.org/en-US/docs/Web/API/Node/childNodes#simple_usage
This is typed weirdly, because apparently you should check for existence here. Technically doing `node.hasChildNodes()` would be correct, but since we tend to serialize stuff here or there I feel this is safer (and we already do that in other places too).
Closes https://github.com/getsentry/sentry-javascript/issues/15948

fix: Check for `node.childNodes` before accessing them
